# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.vm.box = "terrywang/archlinux"
	config.ssh.username = "fuzzy"
	config.ssh.password = "fuzzy"
	config.vm.box_check_update = true
	# config.vm.network "forwarded_port", guest: 80, host: 8080

	# customize for virtualbox use
	config.vm.provider :virtualbox do |vb|
		vb.customize ["modifyvm", :id, "--memory", "2048"]
	end

	# customize for libvirt use
	config.vm.provider :libvirt do |lv|
		lv.memory = 2048
	end

	# VM provisioning
	config.vm.provision :file,
		source: "~/.ssh/id_rsa.pub",
		destination: "/home/fuzzy/.ssh/authorized_keys"

	# TODO: proper provisioning
end
