# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.vm.box = "terrywang/archlinux"
	#config.vm.box = "archlinux"
	#config.ssh.username = "fuzzy"
	#config.ssh.password = "fuzzy"
	config.vm.box_check_update = true
	# config.vm.network "forwarded_port", guest: 80, host: 8080

	# customize for virtualbox use
	config.vm.provider :virtualbox do |vb|
		vb.customize ["modifyvm", :id, "--memory", "2048"]
	end

	# customize for libvirt use
	config.vm.provider :libvirt do |lv|
		lv.memory = 2048
	end

	# disable vagrant folder per default
	config.vm.synced_folder "./", "/vagrant", disabled: true

	# VM provisioning
	#config.vm.provision :file,
	#    source: "~/.ssh/id_rsa.pub",
	#    destination: "~/.ssh/authorized_keys"

	# TODO: proper provisioning
	config.vm.provision :file,
		source: "./files/",
		destination: "/tmp/install/files/"

	config.vm.provision :file,
		source: "./prepare.sh",
		destination: "/tmp/prepare.sh"

	config.vm.provision :file,
		source: "Dockerfile",
		destination: "/tmp/Dockerfile"

	config.vm.provision :shell,
		inline: "cd /tmp && ./prepare.sh"
end
